### ISSUE TITLE
Decomp: RVL/MTX

### ISSUE THREAD

**Issue by wait-wtf** [riidefi/mkw#10]
Tracking issue for decompiling the RVL/MTX library.

RVL/MTX implements maths primitives. nw4r::math depends on it.

Contains `PSMTX*` and `PSVEC*` C functions.

**Checklist**

- [x] PSMTXIdentity
- [x] PSMTXCopy
- [x] PSMTXConcat
- [x] PSMTXConcatArray
- [x] PSMTXInverse
- [x] PSMTXInvXpose
- [x] PSMTXRotRad
- [x] PSMTXRotTrig
- [x] __PSMTXRotAxisRadInternal
- [x] PSMTXRotAxisRad
- [x] PSMTXTrans
- [x] PSMTXTransApply
- [x] PSMTXScale
- [x] PSMTXScaleApply
- [x] PSMTXQuat
- [x] C_MTXLookAt
- [x] C_MTXLightFrustum
- [x] C_MTXLightPerspective
- [x] C_MTXLightOrtho
- [x] PSMTXMultVec
- [x] PSMTXMultVecSR
- [x] C_MTXFrustum
- [x] C_MTXPerspective
- [x] C_MTXOrtho
- [x] PSVECAdd
- [x] PSVECScale
- [x] PSVECNormalize
- [x] PSVECMag
- [x] PSVECDotProduct
- [x] PSVECCrossProduct
- [x] C_VECHalfAngle
- [x] PSVECSquareDistance
- [x] PSQUATMultiply
- [x] PSQUATScale
- [x] PSQUATDotProduct
- [x] PSQUATNormalize
- [x] PSQUATInverse
- [x] C_QUATMtx
- [x] C_QUATLerp
- [x] C_QUATSlerp ~~(Got [Error 10342](https://docs.nxp.com/bundle/GUID-EC03B1E9-8136-4FAF-BAF4-98C41299858D/page/GUID-FCE21026-5F30-4176-8F09-69D2AD067507.html))~~

**Comment by wait-wtf** [comment]
FWIW, here is my (failed) attempt at decompiling C_QuatSlerp: https://github.com/wait-wtf/mkw/blob/3e951cba22415204f93d58397c536b318798ad0a/source/rvl/mtx/rvlQuat.c#L184

Any help to get a matching decompile of this function is welcome.

**Comment by riidefi** [comment]
Probably best to add a nonmatching/asm variant with the new source generator? We can then open a follow-up issue for that lone function.
