### ISSUE TITLE
Progress Badges do not Display

### ISSUE THREAD

**Issue by gudenau** [riidefi/mkw#129]
My browser gets 502 errors when trying to fetch the progress badges and creates links for them instead.

![Untitled](https://user-images.githubusercontent.com/5642329/151678668-0cc88778-551b-4208-b2b3-eb8c435451c5.png)

Pretty self explanatory.

**Comment by terorie** [comment]
Thanks for reporting. Looks like the badge service lost access to the GitHub API. @riidefi We should probably move the badges to GitHub Pages

**Comment by riidefi** [comment]
Thanks for pointing that out. @terorie Would moving the badges to GH pages mean uploading .png files directly to that repository? I remember from past experience (hosting a wasm blob) that Pages uses the most aggressive HTTP caching policy, which was not ideal for dynamic content (solution I used was renaming the wasm blob every time the contents changed). I wonder if that would be a consideration for hosting the badges.

Also related to CI, it looks like the `build_linux` job is failing to install wine now:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wine32:i386 : Depends: libwine:i386 (= 5.0-3ubuntu1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```

**Comment by terorie** [comment]
It's all falling apart 😢 
Will take a look at both today. We should be able to keep the original solution.

**Comment by terorie** [comment]
Root cause of all of this: https://github.com/actions/virtual-environments/issues/4589

**Comment by terorie** [comment]
Badges are fixed. I'm working on improvements that they won't break in the future if Linux CI breaks.
