### ISSUE TITLE
force zero word into sdata

### ISSUE THREAD

**Issue by terorie** [riidefi/mkw#165]
### Problem

RVL/NAND contains empty strings like `strcpy(dest, "")`.
These strings get placed as `0x00000000` in sdata.

This is hard to reproduce from inline assembly:
All of the below allocate an sbss entry in the object file, not sdata.

```c
char c[] = "";
__declspec(section ".sdata") u32 u = 0;
__declspec(section ".sdata") float f = 0.0f;
```

### Task

Figure out a way how to declare a zero word in .sdata and document it.

**Comment by terorie** [comment]
@riidefi @kiwi515 do you have any ideas?

**Comment by kiwi515** [comment]
Have you tried making the data const? I think that might just put it in sbss2 though

**Comment by kiwi515** [comment]
Actually, couldn't you just recreate the `strcpy` call in a stripped function? If you have string pooling on the string constant will stay in the binary.

**Comment by terorie** [comment]
Thanks @kiwi515, yeah decompiling works. 
Const landed in sbss2 and `__declspec(section ".sdata") const char[] = "";` again landed in sbss :D a bit painful.
I was hoping we could find a solution at the inline asm level (for splitting).

**Comment by terorie** [comment]
This has been solved using the `MKW_PATCH` macro. It allows us to place a dummy non-zero value to force a variable into `.sdata`, as well as a patch instruction in a custom section.

This mechanism is fully relocatable. That way we only have to patch the final ELF before transforming into DOL.
