### ISSUE TITLE
Compat: bss ordering & new decomp rules

### ISSUE THREAD

**Issue by terorie** [riidefi/mkw#167]
### Problem

A well known problem with the MWCC compilers is that larger bss data objects have a rather unpredictable order in memory. (Note: with data object, I mean a range of bss bytes created by a symbol declaration)

Trying to match the original order currently requires painfully permuting the source code by hand. Or splitting objects into separate translation units to force order through the linker.

### Proposed solution

TL;DR patch bss relocs.

#### Hacking bss

Instead of fighting with the compiler, let's concede and produce object files that don't feature the original bss data object order. Data order is arbitrary anyways (in theory).

We could simply reorder bss symbols of object files before linkage using a Python script. Reordering usually (👀) doesn't change the size of a section and any references (including symtab/text/sdata) to bss are relocated regardless. Thus we just need to patch these relocations as part of the build script.

The existing metadata files have ample information (slices.csv, symbols.txt):
- The target virtual address of each data object
- The virtual offsets of each section of each translation unit

The script will need to do a bit of number crunching. Basic algorithm that patches an object file:
1. Walk symtab, resolve each bss symbols's virtual address given the bss virtual offset
2. Diff symbols with known addresses from symbols.txt
3. Walk relocations and apply diffs to `r_offset`

This is not a silver bullet and has plenty of problems on its own
- This might not be as trivial as we think in `pyelftools`
- Additional build script bloat, slower builds
- Won't work when linker stripping is enabled
- Won't work for non-exported symbols (I guess we could walk rels instead)
- Won't work if this results in padding differences (still need to permute order to match original padding sizes)

#### New rules

Hacks that reduce accuracy anywhere in the build pipeline are controversial.
We have started to go this route with https://github.com/riidefi/mkw/issues/165. Let's clarify whether such changes are acceptable.
The current (unspoken) assumption that we have about this and other projects goes like this.

> This decomp's Asm/C/C++ sources will produce an identical build of the game given the original build toolchain (or drop-in replacements like elf2dol)

Counterintuitively, I think we should relax our assumptions and consider it acceptable to produce object files that don't feature the original data object order. 

Proposed new rules:

1. Reproducible: The recompiled DOL/RELs must be identical
4. Relocatable: Recompiled object files must be fully relocatable
5. Compiler agnostic: Sources should produce functionally equivalent code even using a different compiler (GCC)

These would give us more freedoms to enhance our workflow and thus move faster.

Low-quality code is still kept out. For example:

- Pointers to absolute addresses (not relocatable)
- Patterns that rely on undefined but predictable behavior seen in CodeWarrior (not compiler agnostic)

---

Would love to hear thoughts from @riidefi

**Comment by EpochFlame** [comment]
Pikmin 2 has some issues with BSS as well; my simple idea was simply to declare/define literally all BSS at the start, and call it via extern. Is this feasible for mkwii?

**Comment by EpochFlame** [comment]
to elaborate- a fake translation unit, e.g. bss.cpp, would contain all the bss definitions for the entire dol. usage would just call them via extern.

**Comment by EpochFlame** [comment]
if that covers your use case, wonderful- seemed far easier to manage than a complex postprocessor

**Comment by SeekyCt** [comment]
That would give different codegen in any files with data pooling, though idk if any of mkw uses that

**Comment by terorie** [comment]
Ideally we would still split up bss according to the original translation units to keep the project composable. For example, we might want to copy a specific C++ source to a mod and leave out the rest. This is where a single global bss or auto-generated arbitrary slices aren't ideal.

But this got me thinking -- We could also have a seperate `<source>_bss.c` for every C source that requires it. That way things stay composable and we can trivially bundle them as `.a` files or merge them in a single `.o` with existing linker tooling. 

In terms of complexity, I would argue splitting bss for every C source is more work than an addition to the post-processing stage. But right now, doing it via source just makes more sense. Thanks for the input @EpochFlame @SeekyCt!
