### ISSUE TITLE
Decomp.me support?

### ISSUE THREAD

**Issue by archanox** [riidefi/mkw#177]
Possibly having MKW up on decomp.me may spread awareness of the decompilation effort?

**Comment by XOlifreX** [comment]
If I remember correctly, @riidefi looked into adding MKW support to decomp.me before but ran into some difficulties. It was being discussed in the GCN/Wii Decomp Discord server not too long ago. However I'm sure the people in the decomp.me Discord server will be able to help out! 😄 Would be fantastic to have MKW on decomp.me, would definitely look into any way to contribute myself!

**Comment by riidefi** [comment]
I haven't looked at the internals of decomp.me, but this should be all the relevant info if someone is interested in adding support.
The developer behind the initial GC/Wii presets implementation had this info, but I don't think mkw support was ever added. The game would be the most complex on the site, with multiple presets and a custom compiler needed.

Shared settings
```py
SHARED = "-nodefaults -align powerpc -enc SJIS -proc gekko -enum int -O4,p -inline auto -W all -fp hardware -Cpp_exceptions off -RTTI off -w notinlined -W noimplicitconv -w nounwanted -nostdinc -msgstyle gcc -lang=c99 -DREVOKART -func_align 4 -sym dwarf-2"
```
Preset settings
```py
HOSTSYS_OPTS = '-ipa file -rostr -sdata 0 -sdata2 0'
RVL_OPTS = '-ipa file'
MSL_LIBC_OPTS = '-ipa file'
NW4R_OPTS = '-ipa file -inline auto -O4,p -pragma \"legacy_struct_alignment on\"'
SPY_OPTS = RVL_OPTS + " -w nounusedexpr -w nounusedarg"
EGG_OPTS = '-ipa function -rostr'
REL_OPTS = HOSTSYS_OPTS + " -pragma \"legacy_struct_alignment on\""
```
Preset names
```py
Mario Kart Wii (DOL)
Mario Kart Wii (RVL_SDK)
Mario Kart Wii (MSL)
Mario Kart Wii (NintendoWare)
Mario Kart Wii (DWC/GameSpy)
Mario Kart Wii (EGG)
Mario Kart Wii (REL)
```
Preset compiler versions
```py
DOL: 4201_127 (patched to simulate _142)
RVL: 4199_60831
MSL: 4201_127 (patched to simulate _142)
NintendoWare: 4201_127 (patched to simulate _142)
DWC/GameSpy: 4199_60831
EGG: 4201_127 (patched to simulate _142)
REL: 4201_127 (patched to simulate _142)
```
Patched 4201_127 compiler:
https://cdn.discordapp.com/attachments/804212941054279722/954854566304833567/mwcceppc_PATCHED.exe

**Comment by XOlifreX** [comment]
Based on the info provided by Riidefi, I have made a start to add MKW support to decomp.me. I haven't been able to test out my implementation yet. Decomp.me doesn't support Windows apparently, so will need to do setup to run decomp.me on Docker, but will do that tomorrow. But regardless, here's what I have already. 😄 

https://github.com/XOlifreX/decomp.me/commit/1c4a5b8292b37d09f585df0abd8eda2f4f93aab0

**Comment by riidefi** [comment]
Nice work! One thing to note is that 127 was not part of "MW for Wii 1.0", so maybe remove that phrase or put it as "internal build"/"simulated version"/something.

**Comment by XOlifreX** [comment]
Update: Didn't have much time today, but made the change Riidefi suggested. Ended up using Ubuntu on a virtual machine and got decomp.me running there. I still have some more setup work left to do to get the decompiling fully working, but will do that tomorrow. Maybe in the meantime, is it possible to provide an example decompiled function with its target asm to use for testing? 😄

**Comment by riidefi** [comment]
This should be a good example, as it highlights specific edge-case behavior we rely on--credit to stebler for the example.
```c
struct my_struct {
    unsigned char arr[0x80];
};

void copy_my_struct(struct my_struct *dst, const struct my_struct *src) {
    *dst = *src;
}
```
Using the REL preset, you should expect individual byte copies (lbz, stb) as opposed to a single 32-bit copies (lwz, stw). This is a version difference between 127 (we don't have) and 142 (we do have) that we have worked around.
```
* struct copies code generation improved.  A change to object alignment made in
2004 (see MTWX15521) inadvertently caused some structs copies to use byte
loads and stores instead of larger loads and stores.  Using byte loads and 
stores exposed a problem with code generation for copying small structs to
and from registers used as return values in little endian.
```
Switching to the RVL_SDK preset should flip this behavior to use 32-bit copies.

**Comment by XOlifreX** [comment]
Alright, an update: mkw has been added to decomp.me!!! 😄 🎊
