### ISSUE TITLE
How to get CodeWarrior compilers ?

### ISSUE THREAD

**Issue by coco875** [riidefi/mkw#182]
I don't know what version is right I found this [this](https://www.nxp.com/design/software/development-software/codewarrior-development-tools/downloads:CW_DOWNLOADS) but I don't know what I need to choose, so I install one but in folder of installation I don't find mwcceppc.exe but by see code of build.py, I see then you use the version 4.2.0.1 Build 127 but how I can find ? because I don't see it in the website (other version of any software is above) so, How to get CodeWarrior compilers ?

**Comment by terorie** [comment]
You can find copies of the CodeWarrior compilers on legally-obtained Wii development kits.

**Comment by riidefi** [comment]
https://github.com/riidefi/mkw/blob/master/.github/workflows/build.yml#L36

**Comment by coco875** [comment]
oh ok tanks, I download it and say if I have problems or other.
