### ISSUE TITLE
Autogenerate data in C sources when creating slices

### ISSUE THREAD

**Issue by em-eight** [riidefi/mkw#228]
Saves us time from modifying the slices and regenerating assembly every time new data is referenced in C code. Will also probably make matching data quick, easier and more beginner friendly.

Doing that requires:
- Adding data definitions in CAsmGenerator corresponding to the data slices
- Referring to those definitions in inline assembly

Project that supports this: https://github.com/SeekyCt/spm-decomp/blob/9a91c42d748a4c9a8a1e8199e5a4d8f36792679b/src/windowdrv.c#L25

**Comment by SeekyCt** [comment]
Just to clarify, that actual c's not auto-generated yet, only the includes it uses
