### ISSUE TITLE
Linux build fails due to wine crashing

### ISSUE THREAD

**Issue by sonich2401** [riidefi/mkw#229]
Trying to build the game with ./build.py works for the most part until it starts building the code. Wine tries to launch the compiler but it fails and crashes with the generic wine crash statement of "page fault". I have included the terminal output log and the sha1sum of my copy of the code warrior compiler.

My computer details:
OS: Ubuntu 20.04.4 LTS x86_64
Kernel: 5.13.0-48-generic
CPU: AMD A9-9425 RADEON R5 2C+3G
Python Version: 3.9

[err.txt](https://github.com/riidefi/mkw/files/9354858/err.txt)
[mwcceppc.exe.sha1.txt](https://github.com/riidefi/mkw/files/9354859/mwcceppc.exe.sha1.txt)
.

**Comment by em-eight** [comment]
Hello, I have been using the compilers on Linux without issues so far. It seems that you have the wrong version of compiler, my sha1sums are `d72ee390287ee8418f1ef664703f6ab5cbf8d0f8` for `4201_142` and `79683505e7fc6bb63e5c169f21623df272dd2262` for `4199_60831`. The specific versions are important because the compiler's binary are patched in the build procedure and the wrong version can be corrupted.

I can send them to you via email, if you send me your address.

**Comment by sonich2401** [comment]
I was a part of a Wii decomp project a while ago and I have a 7z of a lot of versions of the code warrior compiler. I checked the sha1sum of all of my versions and I found matching compilers. It compiles a lot farther now with no wine errors until the linking stage where it is looking for mwldeppc.exe in the /tools folder rather than in /tools/<VERSION>. What version should I make a symlink to? Other than that, I believe my wine issues are solved.

**Comment by em-eight** [comment]
`376bdc5d8fd0e8aef09590116bcda2771a9a2c3f` is my sha1sum of the linker

**Comment by sonich2401** [comment]
Thank you. That helps a lot. Got a lot farther now. It now gives me the error of files compiling to a size that is too large (at least I think that is what it is saying). I believe all of my "compiler missing" issues are fixed. I have uploaded the build.py output. Not quite sure why this is happening seeing as all of the sha1sum's match to the compilers and linkers

[output.txt](https://github.com/riidefi/mkw/files/9374857/output.txt)
.

**Comment by em-eight** [comment]
Hmm, the size mismatch isn't much of an issue, but the linker error is. Can you send the output of that huge linker command in the last `AssertionError`?

**Comment by sonich2401** [comment]
It should be in output.txt if you turn on wordwrap then it should display better

**Comment by em-eight** [comment]
@sonich2401 That's just the python error of the assertion that the linker exited with 0 failed. The linker output is invisible here.

**Comment by sonich2401** [comment]
Running the command outside of python gives no output and only gives the error code of 53. Nothing is printed to the screen.

**Comment by sonich2401** [comment]
That is exactly what I ran. I'm guessing imma have to get a windows VM?

**Comment by em-eight** [comment]
Getting a windows VM is probably going too far. Can you can output from the linker by running it with no arguments? Looks like a linker crash.

**Comment by sonich2401** [comment]
Same error code and no output

**Comment by sonich2401** [comment]
Wine outputs the same error code if I try to run "wine a.exe"

**Comment by sonich2401** [comment]
I figure that I will not get this solved and it sounds like a wine problem and not a mkw-decomp problem. I will close the issue seeing as now I can compile the source files and use objdump to check if my function is matching.

**Comment by stblr** [comment]
Look at what the CI does to get the exact compiler and linker versions.
