### ISSUE TITLE
Memory Address problems

### ISSUE THREAD

**Issue by Quack2Play** [riidefi/mkw#288]
text: at_src=0x000000d4 at_dst=0x000000d4 at_end=0x0037f120 want=0x0037f04c have=0x0037f04c [FAIL]
80540d50: Good=2c060024 Bad=2c060025
 -> This is in { 8053fc4c..80542868 source/game/system/ResourceManager.cpp (text) }
80540d80: Good=392b028c Bad=392b0290
 -> This is in { 8053fc4c..80542868 source/game/system/ResourceManager.cpp (text) }
80540d88: Good=38eb0280 Bad=38eb0284
 -> This is in { 8053fc4c..80542868 source/game/system/ResourceManager.cpp (text) }
80540eac: Good=2c170024 Bad=2c170025
 -> This is in { 8053fc4c..80542868 source/game/system/ResourceManager.cpp (text) }
80540edc: Good=38fd0280 Bad=38fd0284
 -> This is in { 8053fc4c..80542868 source/game/system/ResourceManager.cpp (text) }
80540ee4: Good=393d028c Bad=393d0290
 -> This is in { 8053fc4c..80542868 source/game/system/ResourceManager.cpp (text) }
80541000: Good=2c170024 Bad=2c170025
 -> This is in { 8053fc4c..80542868 source/game/system/ResourceManager.cpp (text) }
80541030: Good=38fd0280 Bad=38fd0284
 -> This is in { 8053fc4c..80542868 source/game/system/ResourceManager.cpp (text) }
80541038: Good=393d028c Bad=393d0290
 -> This is in { 8053fc4c..80542868 source/game/system/ResourceManager.cpp (text) }
80541368: Good=2c1d0024 Bad=2c1d0025
 -> This is in { 8053fc4c..80542868 source/game/system/ResourceManager.cpp (text) }
805414ec: Good=2c000024 Bad=2c000025
 -> This is in { 8053fc4c..80542868 source/game/system/ResourceManager.cpp (text) }
     ctors: at_src=0x0037f120 at_dst=0x0037f120 at_end=0x0037f424 want=0x00000304 have=0x00000304 [OK]
     dtors: at_src=0x0037f424 at_dst=0x0037f424 at_end=0x0037f430 want=0x0000000c have=0x0000000c [OK]
    rodata: at_src=0x0037f440 at_dst=0x0037f440 at_end=0x003a28f0 want=0x000234b0 have=0x000234b8 [SIZE]
80890ab8: Good=5f726564 Bad=6e775f62
 -> This is in { 80890490..80890d10 source/game/system/ResourceManager.cpp (rodata) }
80890abc: Good=0 Bad=696b6500
 -> This is in { 80890490..80890d10 source/game/system/ResourceManager.cpp (rodata) }
80890ac0: Good=5f626c75 Bad=5f726564
 -> This is in { 80890490..80890d10 source/game/system/ResourceManager.cpp (rodata) }
80890ac4: Good=65000000 Bad=0
 -> This is in { 80890490..80890d10 source/game/system/ResourceManager.cpp (rodata) }
80890ac8: Good=0 Bad=5f626c75
 -> This is in { 80890490..80890d10 source/game/system/ResourceManager.cpp (rodata) }
80890acc: Good=0 Bad=65000000
 -> This is in { 80890490..80890d10 source/game/system/ResourceManager.cpp (rodata) }
80890ad0: Good=5f320000 Bad=0
 -> This is in { 80890490..80890d10 source/game/system/ResourceManager.cpp (rodata) }
80890ad4: Good=5f340000 Bad=0
 -> This is in { 80890490..80890d10 source/game/system/ResourceManager.cpp (rodata) }
80890ad8: Good=2f656172 Bad=5f320000
 -> This is in { 80890490..80890d10 source/game/system/ResourceManager.cpp (rodata) }
80890adc: Good=74682e62 Bad=5f340000
 -> This is in { 80890490..80890d10 source/game/system/ResourceManager.cpp (rodata) }
80890ae0: Good=72726573 Bad=2f656172
 -> This is in { 80890490..80890d10 source/game/system/ResourceManager.cpp (rodata) }
      data: at_src=0x003a28f0 at_dst=0x003a2900 at_end=0x003cd0f4 want=0x0002a804 have=0x0002a804 [OK]
       bss: at_src=0x00000000 at_dst=0x00000000 at_end=0x000078b0 want=0x000078b0 have=0x000078b0 [OK]
[REL] Oof: Output doesn't match.
ninja: build stopped: subcommand failed.

The thing i was trying to do was const char* VEHICLE_NAMES[] = {
    "sdf_kart", "mdf_kart", "ldf_kart", "sa_kart", "ma_kart", "la_kart",
    "sb_kart",  "mb_kart",  "lb_kart",  "sc_kart", "mc_kart", "lc_kart",
    "sd_kart",  "md_kart",  "ld_kart",  "se_kart", "me_kart", "le_kart",
    "sdf_bike", "mdf_bike", "ldf_bike", "sa_bike", "ma_bike", "la_bike",
    "sb_bike",  "mb_bike",  "lb_bike",  "sc_bike", "mc_bike", "lc_bike",
    "sd_bike",  "md_bike",  "ld_bike",  "se_bike", "me_bike", "le_bike",
    "nw_bike"
};
nw_bike is new.

I have asked ChatGPT how i can fix it but it kept saying the most unclear things and was not helping me.

**Comment by em-eight** [comment]
Your binary is still being built, it's just that the build system checks that the result matches the original, and because you have changes it does not.

You will be able to find your binaries at the artifacts folder. They will likely not be usable since the decomp is not guaranteed to be shiftable yet

**Comment by Quack2Play** [comment]
Can I then just make the u8 _00[0xc94 - 0x0]; be u8 _00[0xd20 - 0x0[; so the file will be bigger and i will then just work and not corrupt the entire game?

**Comment by Quack2Play** [comment]
nevermind i fixed it myself it was the header file i had messed up by not adding a new name :)
Yup i am trying to make extra characters and extra vehicles (extra buttons) ;)
