### ISSUE TITLE
Improved ASM generation

### ISSUE THREAD

**Issue by wait-wtf** [riidefi/mkw#29]
**Summary**: Tracking issue for improved ASM structuring

**Context**
The code parts that have not been decompiled yet are kept as assembly `asm/*.s` files.
These files are generated from the game's binary executables.
The code generating backend for this uses a naive slicing approach:
A "slices table" (slices.csv) keeps track of which address ranges come from ASM or C/C++ sources.
This table only defines the C/C++ slices. The ASM slices are derived by looking at the "gaps".
These gaps get constructed by ASM files for each section (text, data, ...).

**Problems**
1. The current ASM files are massive and span many different unrelated parts of the program.
2. They tend to cause a lot of merge conflicts due to their size, forcing us into a linear work flow.
3. The content is hard to read due to the lack of labels/symbols.
4. Changes to ASM files immediately get lost because `gen_asm` is quite destructive.

**Tasks**
* Build a centralized symbol table (#26)
* Update slices.csv to support explicit ASM slices so we can create finer scoped `.s` files. This fixes problems 1, 2, 4
* Consider defining symbols in the ASM sources instead of in the linker command file to fix problem 3

**Comment by riidefi** [comment]
Another option could be requiring gen_asm on build, and not committing any actual asm files. But there's probably something to be said about having readable asm in the repo and not requiring an external tool to contribute.
I'd be more a fan of outputting .c files with asm in them, which could speed up incrementally decompiling a TU.
Of course improving the asm / adding symbols will be necessary for us to switch the raw branches "bl -0x454" into labeled "bl FuncName" to create relocations to enable building with variable function sizes.

**Comment by wait-wtf** [comment]
I will be working on a C generator as discussed in Discord.
