### ISSUE TITLE
Add Linux build to Github CI

### ISSUE THREAD

**Issue by wait-wtf** [riidefi/mkw#35]
To ensure this project keeps working for Linux folks, we should add a CI configuration that runs on Linux. CodeWarrior Windows-only tooling runs fine under Wine.

**Comment by stblr** [comment]
Current issues with Linux:
- [ ] #84
- [ ] File separators: the lcf must use `\`, otherwise `/` works correctly.
- [ ] Wine doesn't work with subprocess, some hack is to add `shell=True` and to convert the whole command line to a string, but there is probably a better way to do it.

**Comment by wait-wtf** [comment]
My bad, I did not realize wine is not a normal command. In the past we used `system()`.
As long as it works, I'm fine with using subprocess + shell.
`" ".join(arguments)` should work, even if it's ugly, but I don't think we're going to have much quoting issues.
In case we do, we can catch them early using CI.
Let's use [wineconsole(1)](https://linux.die.net/man/1/wineconsole) with ncurses backend if possible. 

The alternative is reading up on Wine architecture and figuring out how to instruct `wineserver` directly from Python to spawn new programs.

**Comment by riidefi** [comment]
I've added a quick fix for paths (https://github.com/riidefi/mkw/blob/master/mkwutil/gen_lcf.py#L16-L20) and wine calls (shell=True) to support building on OSX.

Very open to rewriting either with a better way, especially with how we use subprocess.

**Comment by terorie** [comment]
The pathlib way of doing this would be `str(PurePosixPath(windows_path))`.
