### ISSUE TITLE
Deploy graphic.py to GitHub Pages

### ISSUE THREAD

**Issue by wait-wtf** [riidefi/mkw#36]
`graphic.py` is a neat script that visualizes the compilation process by compiling a static HTML file.
It would be a shame to let this go unnoticed.

GitHub offers an easy way to continually deploy auto-generated websites to their GitHub Pages hosting services. https://github.com/marketplace/actions/deploy-to-github-pages

The site would be accessible under https://riidefi.github.io/mkw/

**Comment by riidefi** [comment]
That'd be really neat. Wonder how difficult it'd be to embed into the README? Would we have to bake down to a static image?

**Comment by wait-wtf** [comment]
@riidefi GitHub's Markdown / HTML viewer on `github.com` is fairly restrictive and won't allow embedding any kind of fancy CSS. Using an image is a good idea. If we don't want to invest time into a new renderer (like canvas), we can probably use web automation. These days it's quite advanced so it's possible to spawn a headless Chromium in CI to bake a PNG and upload it to GitHub Pages. Then we can embed the image pointing to GitHub Pages in the README.
If we do so, it would be nice to work on more appealing art first (#30) like in a cheesy style of MKW win screen or player listing or something.
