### ISSUE TITLE
Python Restructure

### ISSUE THREAD

**Issue by riidefi** [riidefi/mkw#55]
I think we can reorganize the python code structure to be a bit more clear.

Suggested changes:
- Move sources.py to root directory away from buildsystem internals
- dol.py, rel.py, etc. -> lib
- rel_header.bin -> data
- percent_decompiled.py, graphic.py -> progress
- slices_test.py -> tests

**Comment by wait-wtf** [comment]
Would be good to have tests in the same module as the code they are verifying.

**Comment by riidefi** [comment]
Ah, good point. I'd also like to pull some of the mkw specific code out of the library modules. e.g. SliceTable.load_dol_slices could be extracted out and into a global "project" object that has all possible mkw-specific data a script might want.
