### ISSUE TITLE
Set up Doxygen CI

### ISSUE THREAD

**Issue by terorie** [riidefi/mkw#92]
The README.md mentions that source files contain Doxygen annotations.
Let's set up a GitHub Action to publish the latest docs to https://riidefi.github.io/mkw/docs/

**Comment by riidefi** [comment]
We might want to consider Sphinx/something else. Definitely should have something, though.

**Comment by terorie** [comment]
@riidefi Hmm, isn't Sphinx for Python only though? Just let me know what kind of doc generators you want and I'll build them.
